baseURL = 'http://chillax.zone/'
googleAnalytics = 'G-QW69RMV678'
languageCode = 'en-us'
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "monokai"
theme = 'archie'
title = 'chillax.zone'

[params]
katex = false
mathjax = false
mode = 'dark'
subtitle = 'making and breaking stuff, more often the latter'
useCDN = false

[[params.social]]
icon = 'github'
name = 'GitHub'
url = 'https://github.com/samuria'

[[menu.main]]
name = 'home'
url = '/'
weight = 1

[[menu.main]]
name = 'posts'
url = '/posts'
weight = 2

# [[menu.main]]
# name = 'about'
# url = '/about'
# weight = 3
